package com.example.skeleton.dao;

import com.example.skeleton.model.Actor;
import com.example.skeleton.model.ActorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    long countByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    int deleteByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    int insertSelective(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    List<Actor> selectByExample(ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Actor record, @Param("example") ActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Mon Mar 13 12:05:19 CST 2017
     */
    int updateByExample(@Param("record") Actor record, @Param("example") ActorExample example);
}